parameters:
  front.factory.class: Spiffy\Service\Factory\Front
  layout.factory.class: Spiffy\Service\Factory\Layout
  view.factory.class: Spiffy\Service\Factory\View

services:
  front:
    factory_class: %front.factory.class%
    factory_method: get
    
  layout:
    factory_class: %layout.factory.class%
    factory_method: get
    
  view:
    factory_class: %view.factory.class%
    factory_method: get
