parameters:
  front.factory.class: Spiffy\Zend\Service\Front
  layout.factory.class: Spiffy\Zend\Service\Layout
  view.factory.class: Spiffy\Zend\Service\View
  
services:
  front:
    factory_class: %front.factory.class%
    factory_method: get
    
  layout:
    factory_class: %layout.factory.class%
    factory_method: get
    
  view:
    factory_class: %view.factory.class%
    factory_method: get